USE SQL_PRACTISE;

# DATA MANIPULATION LANGUAGE (DML)

# 1.INSERT | SINGLE | MULTIPLE ROW ADD
INSERT INTO ACCOUNT (id, name, balance) VALUES (5, 'Akash Bhisikar', 20001);
INSERT INTO ACCOUNT (id, name, balance) VALUES 
    (1, 'Chirag Bhisikar', 30001),
    (2, 'Haresh Bhisikar', 40000),
    (3, 'Ronak Bhisikar', 50000);
INSERT INTO ACCOUNT VALUES (4, 'Aman Bhisikar', 60001);
SELECT * FROM ACCOUNT;

# 2. UPDATE
UPDATE ACCOUNT SET name = 'Minesh Bhisikar', balance = 80000 WHERE id = 3;
UPDATE ACCOUNT SET balance = 80000;

# 3. DELETE
DELETE FROM ACCOUNT WHERE id = 5; # DELETE ROWS WHERE id = 5
DELETE FROM ACCOUNT; # DELETE ALL ROWS OF TABLE

# DELETE ON DELETE CASCADE | ON DELETE SET NULL
DROP TABLE CUSTOMER;
DROP TABLE ORDER_DETAILS;

CREATE TABLE CUSTOMER(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    address VARCHAR(50),
    gender VARCHAR(2),
    city VARCHAR(15),
    pincode INTEGER
);

CREATE TABLE ORDER_DETAILS(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    delivery_date DATETIME,
    customer_id INT UNSIGNED,
    # FOREIGN KEY(customer_id) REFERENCES CUSTOMER(id)
    # FOREIGN KEY(customer_id) REFERENCES CUSTOMER(id) ON DELETE CASCADE
    FOREIGN KEY(customer_id) REFERENCES CUSTOMER(id) ON DELETE SET NULL
);

INSERT INTO CUSTOMER VALUE(1,'A', 'Ahmedabad','M', 'Ahmedabad', 382415);
INSERT INTO ORDER_DETAILS VALUE(1,'2022-04-22 10:34:23',1);

DELETE FROM CUSTOMER WHERE id = 1;
SELECT * FROM ORDER_DETAILS;

